name: video_calling_app_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # Core UI
  cupertino_icons: ^1.0.8

  # State, routing, theming, logging
  provider: ^6.1.1
  go_router: ^14.6.2
  logger: ^2.5.0

  # Env/config
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2

  # Networking
  dio: ^5.7.0
  socket_io_client: ^2.0.3+1

  # WebRTC and permissions
  flutter_webrtc: ^0.12.3
  permission_handler: ^11.3.1

  # Local storage
  sqflite: ^2.4.2
  path: ^1.9.0

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
